// Generated by https://quicktype.io

export interface CreatorsData {
  offset: number;
  limit: number;
  total: number;
  count: number;
  results: Creators[];
}

export interface Creators {
  id: number;
  firstName: string;
  middleName: string;
  lastName: string;
  suffix: string;
  fullName: string;
  modified: string;
  thumbnail: Thumbnail;
  resourceURI: string;
  comics: Comics;
  series: Comics;
  stories: Stories;
  events: Comics;
  urls: URL[];
}

interface Comics {
  available: number;
  collectionURI: string;
  items: ComicsItem[];
  returned: number;
}

interface ComicsItem {
  resourceURI: string;
  name: string;
}

interface Stories {
  available: number;
  collectionURI: string;
  items: StoriesItem[];
  returned: number;
}

interface StoriesItem {
  resourceURI: string;
  name: string;
  type: ItemType;
}

enum ItemType {
  Cover = 'cover',
  Empty = '',
  InteriorStory = 'interiorStory',
}

interface Thumbnail {
  path: string;
  extension: Extension;
}

enum Extension {
  Jpg = 'jpg',
}

interface URL {
  type: URLType;
  url: string;
}

enum URLType {
  Detail = 'detail',
}
